Repository wecode-bootcamp-korea/fullstack2-1st-keudaran-studio-frontend, pull requests merged in 2021-10, with the labels that each got.

#11 [성지수] 상품 상세페이지 기본 레이아웃 구성 밑 컴포넌트 분류 완료
  package-lock.json
  package.json
  src/index.js
  src/pages/ProductDetail/ProductContents/ProductContents.js
  src/pages/ProductDetail/ProductContents/ProductContents.scss
  src/pages/ProductDetail/ProductDescription/ProductDescription.js
  src/pages/ProductDetail/ProductDescription/ProductDescription.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductMiddleNav/ProductMiddleNav.js
  src/pages/ProductDetail/ProductMiddleNav/ProductMiddleNav.scss
  src/pages/ProductDetail/ProductPhoto/ProductPhoto.js
  src/pages/ProductDetail/ProductPhoto/ProductPhoto.scss
  src/pages/ProductDetail/data.json
  src/styles/_common.scss
  src/styles/_mixin.scss
Labels: Status: 피어 리뷰 요청

#21 [이예봄] footer 구현 완료
  public/images/kedaran2.svg
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterData.js
Labels: Status: 피어 리뷰 요청

#12 [이욱창] sign in 기능 구현 완료
  package-lock.json
  src/pages/Sign/SignIn/SignIn.js
  src/pages/Sign/SignIn/SignIn.scss
  src/pages/Sign/SignIn/SignInBox.js
  src/pages/Sign/SignIn/SignInBox.scss
Labels: Status: 피어 리뷰 요청

#18 [신기철] Add : review 레이아웃 구현중
  src/components/Review/Review.js
  src/components/Review/Review.scss
  src/components/Review/star.html
  src/components/Review/star.png
Labels: Status: 피어 리뷰 요청

#31 [김시원] Best Review Carousel 구현
  src/components/BestReviewCarousel/BestReviewCarousel.js
  src/components/BestReviewCarousel/BestReviewCarousel.scss
  src/components/BestReviewCarousel/MockData.js
  src/components/BestReviewCarousel/ReviewCard.js
  src/components/BestReviewCarousel/ReviewCard.scss
  src/pages/Main/Main.js
Labels: status: 기본기능 구현중

#34 [김시원] 슬라이드 배너 : 좌우 이동 버튼 위치조정
  public/images/carousel0.png
  public/images/carousel1.png
  public/images/carousel3.png
  src/components/Carousel/Carousel.js
  src/components/Carousel/Carousel.scss
  src/components/Carousel/SlideImage.js
  src/components/Carousel/SlideImage.scss
  src/components/Carousel/carouselMockData.js
  src/components/Carousel/mockData.js
  src/pages/Main/Main.js
Labels: Status: Accepted

#35 Feature/best review carousel
  package.json
  src/components/BestReviewCarousel/BestReviewCarousel.js
  src/components/BestReviewCarousel/BestReviewCarousel.scss
  src/components/BestReviewCarousel/ReviewCard.js
  src/components/BestReviewCarousel/ReviewCard.scss
Labels: Status: Accepted

#30 [김시원] MainList 컴포넌트
  public/images/carousel0.png
  src/components/BestReviewCarousel/BestReviewCarousel.js
  src/components/BestReviewCarousel/ReviewCard.js
  src/components/BestReviewCarousel/ReviewCard.scss
  src/components/BestReviewCarousel/bestReviewMockData.js
  src/components/Carousel/Carousel.js
  src/components/Carousel/SlideImage.js
  src/components/Carousel/carouselMockData.js
  src/components/MainList/MainList.js
  src/components/MainList/MainList.scss
  src/components/MainList/MainListMockData.js
  src/components/MainList/MainProductCard.js
  src/components/MainList/MainProductCard.scss
  src/pages/Main/Main.js
Labels: status: 기본기능 구현중

#43 [이욱창] 로그인화면의 회원가입링크, 비밀번호찾기 링크 활성화
  src/pages/Sign/SignIn/SignIn.js
  src/pages/Sign/SignIn/SignInBox.js
Labels: Status: 피어 리뷰 요청
